Finished Test API Using MySQL Database
web-masons/pyramid-zappa-api-boilerplate pull request #12
Opened 2017-07-10 14:09 UTC by Nico005

Demo API.
Connects to a MySQL Database.
Creates a single table called users, you are able to do all the CRUD requests via an API

### Demo

Curl examples : 
#Get a list of all users in the database
curl http://<server_ip:port>/all_users

#Get a single user in database using the users id
curl http://<server_ip:port>/single_user/<users_id>

#Insert a User
curl -X POST -H "Content-Type: application/json" -d '{<columns and values>}' http://<server_ip:port>/create_new_user**
E.g : 
curl -X POST -H "Content-Type: application/json" -d '{"name": "Test User", "super_hero":"1"}' http://0.0.0.0:6543/create_new_user

#Update a User
curl -X PUT -H "Content-Type: application/json" -d '{<columns and values to be updated>}' http://<server_ip:port>/update_user/<user_id_to_update>

#Delete a User
curl -X DELETE http://<serverip:port>/delete_user/<user_id_to_delete>

### Notes

You will need to run the bootstrap script to install all requirements.
MySQL etc

## Testing Instructions

- Run the bootstrap script
- Run the setup file in the project    :  python setup.py develop
- Update the development.ini / production.ini connection details with your database credentials
- Run the initialize_battlecry_proj_db development.ini
- Start Project to test with the above curl examples pserve development.ini --reload

2017-07-10 14:58 UTC, markdia requested changes
I'm not sure how to actually review the git submodule.  There is probably an alternative solution to using a submodule that we should look at.

2017-07-10 14:58 UTC, markdia commented on script/bootstrap
> +sudo apt-get install mysql-server-5.7
these things should be done in the provisioner - ansible

2017-07-10 15:02 UTC, oakensoul commented on script/bootstrap
> +sudo apt-get install mysql-server-5.7
Also, we should be using RDS to run a mysql server, you likely don’t want to install the server inside the vagrant box itself.

2017-07-10 15:03 UTC, oakensoul commented on Vagrantfile
> +hosts_aliases = %w(warcry.localdomain "warcry.web-masons.org")
This is the Pyzapi project, so you don’t want to change the name of the project to something else. If you’re making a copy of the project, you could do that, but we don’t want to change the base project.

2017-07-10 15:12 UTC, oakensoul requested changes
The one thing I’m concerned with is that in a few places, there are core changes to the base project that would bring it out of alignment of the goals of the project which is primarily that it is re-usable. If we’re going to place examples of “how to use it” in here, they should be inside an ‘/examples/‘ folder with some documentation for what the example shows.

Also, I noticed in your PR comments some of the ideas you had for your example, we should sit down and chat about some good REST API practices. I think I can offer you some direction that would be more in line with the REST API best practices. I can’t see your submodule from here, so it’s hard to see your implementation.

2017-07-10 15:12 UTC, oakensoul commented on Vagrantfile
> +  config.vm.synced_folder ".", "/home/nico/",
We shouldn’t be changing the /vagrant folder. By changing it to a users folder that would mean all users in the future would have to share it.

2017-07-10 15:12 UTC, oakensoul commented on Vagrantfile
> +      vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 2000 ]
Why are we changing the time threshold here? Was it causing issues? I’d love to understand a bit more.

2017-07-10 15:12 UTC, oakensoul commented on script/bootstrap
> +sudo pip install virtualenv virtualenvwrapper
I have a good example for how to deal with the virtual env stuff. Let me see if I can load that up for you tonight.

2017-07-11 10:11 UTC, Nico005 commented on script/bootstrap
> +sudo apt-get install mysql-server-5.7
Ill take this out the script and connect MySQL on Amazon RDS

2017-07-11 10:12 UTC, Nico005 commented on Vagrantfile
> +hosts_aliases = %w(warcry.localdomain "warcry.web-masons.org")
Will revert project name back to "pyzappi"

2017-07-11 10:14 UTC, Nico005 commented on Vagrantfile
> +  config.vm.synced_folder ".", "/home/nico/",
sorry this slipped through, was done as a test.. as was still getting the hang of vagrant :)
I will revert and sync to the vagrant folder

2017-07-11 10:31 UTC, Nico005 commented on Vagrantfile
> +      vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 2000 ]
I had some network issues on my side, tested with the threshold of 1000 and seems fine now, will revert and commit

2017-07-12 08:47 UTC, closed without merging